# Generated by Django 3.1.7 on 2021-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("alias", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="alias", name="end", field=models.DateTimeField(null=True)
        )
    ]
